### ISSUE TITLE
App Crash in Compose Material 3 version 1.3.0 or above

### ISSUE THREAD

**Issue by EvilHydra09** [arpitkatiyar1999/Country-Picker#4] opened 2024-11-28 10:07 UTC
java.lang.NoSuchMethodError: No static method BasicAlertDialog(Lkotlin/jvm/functions/Function0;Landroidx/compose/ui/Modifier;Landroidx/compose/ui/window/DialogProperties;Lkotlin/jvm/functions/Function2;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material3/AndroidAlertDialog_androidKt; or its super classes (declaration of 'androidx.compose.material3.AndroidAlertDialog_androidKt' appears in /data/app/~~MnOqQKmpDr3D0Rg7rwDTLQ==/com.dating.sacrenacompose-DBqq56eBCb7IUeeYsO39Cw==/base.apk!classes18.dex)
                                	at com.arpitkatiyarprojects.countrypicker.CountrySelectionDialogKt.CountrySelectionDialog(CountrySelectionDialog.kt:75)
                                	at com.arpitkatiyarprojects.countrypicker.CountryPickerKt.CountryPicker(CountryPicker.kt:77)
                                	at com.arpitkatiyarprojects.countrypicker.CountryPickerOutlinedTextFieldKt$CountryPickerOutlinedTextField$3.invoke(CountryPickerOutlinedTextField.kt:98)
                                	at com.arpitkatiyarprojects.countrypicker.CountryPickerOutlinedTextFieldKt$CountryPickerOutlinedTextField$3.invoke(CountryPickerOutlinedTextField.kt:97)

**Comment by Abhay-cloud** [comment] 2024-12-05 06:29
Yes, It has an issue. No matter what version you use. I tried compose bom 2023.08.00 (material3 1.1.1 ig), 2024.08.00(1.2.1), 2024.10.00(1.3.0), but it did not work. 
![image](https://github.com/user-attachments/assets/7a5fe8bf-7194-4dfd-a7b8-3d1bbdecfe15)

**Comment by bs-yash-khatri** [comment] 2024-12-16 11:23
Hello @arpitkatiyar1999 Did you find any solution for this issue?

**Comment by arpitkatiyar1999** [comment] 2024-12-16 13:23
Hi @bs-yash-khatri 

We are currently investigating the issue . To gain better insights and identify the root cause, we would require additional details regarding your project's build configuration.

Could you please share the following files:

The build.gradle file (both at the project and module level).
The libs.versions.toml file (if your project uses version catalogs).
This information will help us ensure that there are no version mismatches or configuration issues affecting the dependencies.

**Comment by abdallahmehiz** [comment] 2024-12-24 15:18
You just need to update the compose bom in the library and stop using the deprecated BasicAlertDialog.

**Comment by arpitkatiyar1999** [comment] 2024-12-24 17:14
Hi @abdallahmehiz,

I wanted to share that BasicAlertDialog is not deprecated, and I was able to resolve the issue successfully. It has been addressed in version 2.0.1.

Thank you for your guidance!

**Closed by arpitkatiyar1999** 2024-12-24 17:14 UTC

**Comment by abdallahmehiz** [comment] 2024-12-24 20:35
Thank you for the quick release 👍
